import { Poppins } from "next/font/google";
import "./global.css";
import StyledComponentsRegistry, { BODY } from "@/lib/registry";
import Nevigation from "@/components/nevigationBar/Nevigation";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <BODY className={poppins.className}>
        <StyledComponentsRegistry>
          <Nevigation />
          {children}
        </StyledComponentsRegistry>
      </BODY>
    </html>
  );
}
